Do not use compare_and_swap for db update
comit-network/comit-rs pull request #3335
Opened 2020-10-26 03:43 UTC by D4nte

Backward compatibility is maintained to allow newer software to
deserialize older data.
We do not try to guarantee that older data serialised the same way than
newer data.
Which means that `compare_and_swap` fails if the swap was created with
an older version of the software.

As we do not cater for concurrent update of the db, and we just retrieved
the swap to update few lines ago, it is ok to not check again.

This resolves the issue encountered when trying to archive a swap
created before the archive swap feature was introduced.

2020-10-26 04:49 UTC, thomaseizinger requested changes
Compare-and-swap is the basic primitive of any lock-free algorithm. Not using it without introducing any other kind of locking is opening the door to data races ...

If this is what we have to do to work with sled then I don't think it is a good fit for our usecase. We should strongly consider moving to something else.

Requested changes because I think there is stale code. I commented inline.

2020-10-26 04:49 UTC, thomaseizinger commented on nectar/src/database.rs
> +    struct Swap0_1_0 {
What do we need this struct for?

2020-10-26 05:34 UTC, D4nte commented on nectar/src/database.rs
> +    struct Swap0_1_0 {
stale code indeed. Thanks!

2020-10-26 05:36 UTC, D4nte commented
> If this is what we have to do to work with sled then I don't think it is a good fit for our usecase. We should strongly consider moving to something else. We don't have to address this immediately though.

It looks like to me is that sled is lower level than I first anticipated.

The proper solution here (except for using something else than sled) would be to migrate existing data to the new format so that compare and swap can still be used.

2020-10-26 08:08 UTC, thomaseizinger commented
> > If this is what we have to do to work with sled then I don't think it is a good fit for our usecase. We should strongly consider moving to something else. We don't have to address this immediately though.
> 
> It looks like to me is that sled is lower level than I first anticipated.
> 
> The proper solution here (except for using something else than sled) would be to migrate existing data to the new format so that compare and swap can still be used.

I agree but I don't want us to invest a lot of time into that to be honest :/

2020-10-26 08:37 UTC, D4nte commented
> > > If this is what we have to do to work with sled then I don't think it is a good fit for our usecase. We should strongly consider moving to something else. We don't have to address this immediately though.
> > 
> > 
> > It looks like to me is that sled is lower level than I first anticipated.
> > The proper solution here (except for using something else than sled) would be to migrate existing data to the new format so that compare and swap can still be used.
> 
> I agree but I don't want us to invest a lot of time into that to be honest :/

I am pretty sure it's 10 line of code. I am keen to try. Let's see.

2020-10-28 03:02 UTC, D4nte commented
10 lines, more or less 200 https://github.com/comit-network/comit-rs/pull/3343

2020-10-28 03:02 UTC, closed without merging