Introduce SwapRequestHandler for Bob
comit-network/comit-rs pull request #443
Opened 2018-11-19 08:21 UTC by thomaseizinger

Resolves #417.

This is the 2nd preparation step for doing #380. After this, we only need to "fill-in" the instantiation of the state machine in the `SwapRequestHandler` for Alice and Bob.

2018-11-19 23:21 UTC, LLFourn approved these changes
Nice work. Approving but would prefer the enums be renamed to ..`SwapRequestKind` rather than `SwapRequests` (and wherever else you feel it would be appropriate on Asset and Ledger etc).

2018-11-20 00:23 UTC, D4nte reviewed
First pass

2018-11-20 00:43 UTC, D4nte requested changes
Couple of comment regarding `unwrap()`.

2018-11-20 00:59 UTC, D4nte approved these changes

2018-11-20 01:59 UTC, merged