Allow Bob to accept a swap
comit-network/comit-rs pull request #464
Opened 2018-11-21 06:10 UTC by thomaseizinger

This PR adds two routes to the HTTP API:

- accept
- decline

These are the two actions that Bob can perform when presented with a swap request. At the moment, only `accept` is implemented but this is the much more difficult one. If he accepts, his response is used for two things:

- it is sent back to Alice
- his own state machine is advanced into the next state and starts listening for Alice to deploy the first contract

2018-11-21 10:46 UTC, D4nte requested changes
Well done @thomaseizinger for finishing off this PR! Few minor comments

2018-11-22 00:31 UTC, bonomat reviewed
Good job. I just added some comments.

2018-11-22 00:38 UTC, LLFourn approved these changes

2018-11-22 03:04 UTC, D4nte approved these changes

2018-11-22 03:34 UTC, merged