Bob redeems his beautiful Ether ༼ つ ◕_◕ ༽つ
comit-network/comit-rs pull request #508
Opened 2018-11-29 06:31 UTC by thomaseizinger

Resolves #388.

2018-11-29 06:36 UTC, D4nte requested changes
Please check Bob can spend its bitcoin :D

2018-11-29 12:35 UTC, D4nte approved these changes

2018-11-30 03:24 UTC, luckysori requested changes

2018-11-30 03:49 UTC, luckysori approved these changes
Love the improved logs!

2018-11-30 03:55 UTC, LLFourn approved these changes
Nice! Made one suggestion. Approved.

2018-11-30 04:16 UTC, merged